version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      nginx_net:
        ipv4_address: 172.16.0.2
    volumes:
      - ./conf.d:/etc/nginx/conf.d

networks:
  nginx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
