version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8001:80'
    volumes:
      - ./src:/src
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./src:/src
  mysql:
    image: mysql:5.7
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    ports:
      - '3001:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo
      MYSQL_DATABASE: foo
